In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df=pd.read_csv("data/dataset.csv")
df

,Product_ID,Product_Name,Brand,Category,Subcategory,SKU,City,Date,Day_of_Week,Month,...,Festival_Impact_Score,Weather_Impact_Score,Price_Volatility_30d,Price_to_Competitor_Ratio,Stock_Days_Remaining,Demand_Momentum_7d,Revenue_Per_Unit,Price_Rank_in_Category,Fuel_Price_INR_Proxy,Optimal_Price
0,PROD-ELEC-001,Wireless Noise Cancelling Headphones Pro,SoundPulse,Electronics,Audio,SKU-ELEC-001,Ahmedabad,2023-01-15,6,1,...,3.00,0.0,0.00,0.982,3.6,1.00,1322.41,1,110.12,5248.95
1,PROD-ELEC-001,Wireless Noise Cancelling Headphones Pro,SoundPulse,Electronics,Audio,SKU-ELEC-001,Ahmedabad,2023-01-16,0,1,...,0.60,0.0,0.00,0.963,3.6,1.00,1322.41,1,110.34,4807.67
2,PROD-ELEC-001,Wireless Noise Cancelling Headphones Pro,SoundPulse,Electronics,Audio,SKU-ELEC-001,Ahmedabad,2023-01-17,1,1,...,0.69,0.0,0.00,1.027,4.2,1.00,1322.41,1,111.30,4683.22
3,PROD-ELEC-001,Wireless Noise Cancelling Headphones Pro,SoundPulse,Electronics,Audio,SKU-ELEC-001,Ahmedabad,2023-01-18,2,1,...,0.80,0.0,0.00,1.035,4.1,1.00,1322.41,1,110.15,4725.43
4,PROD-ELEC-001,Wireless Noise Cancelling Headphones Pro,SoundPulse,Electronics,Audio,SKU-ELEC-001,Ahmedabad,2023-01-19,3,1,...,0.92,0.0,0.00,1.015,4.0,1.00,1322.41,1,111.21,4735.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145893,PROD-SPOR-120,Push-Up Stand Bars with Cushioned Grips,IronCore,Sports & Fitness,Strength Training,SKU-SPOR-120,Surat,2026-07-29,2,7,...,0.22,0.0,23.93,0.987,6.0,1.04,144.21,2,137.26,492.97
145894,PROD-SPOR-120,Push-Up Stand Bars with Cushioned Grips,IronCore,Sports & Fitness,Strength Training,SKU-SPOR-120,Surat,2026-07-30,3,7,...,0.25,0.0,24.57,1.002,5.9,1.06,144.21,2,136.03,485.13
145895,PROD-SPOR-120,Push-Up Stand Bars with Cushioned Grips,IronCore,Sports & Fitness,Strength Training,SKU-SPOR-120,Surat,2026-07-31,4,7,...,0.29,-0.6,25.14,0.937,5.9,1.04,144.21,2,137.73,472.25
145896,PROD-SPOR-120,Push-Up Stand Bars with Cushioned Grips,IronCore,Sports & Fitness,Strength Training,SKU-SPOR-120,Surat,2026-08-01,5,8,...,0.34,-0.6,25.66,0.959,5.8,1.03,144.21,2,137.73,469.57
145897,PROD-SPOR-120,Push-Up Stand Bars with Cushioned Grips,IronCore,Sports & Fitness,Strength Training,SKU-SPOR-120,Surat,2026-08-02,6,8,...,0.39,-0.6,26.12,0.989,5.6,1.04,159.07,2,137.73,482.63

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145898 entries, 0 to 145897
Data columns (total 71 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Product_ID                    145898 non-null  object
 1   Product_Name                  145898 non-null  object
 2   Brand                         145898 non-null  object
 3   Category                      145898 non-null  object
 4   Subcategory                   145898 non-null  object
 5   SKU                           145898 non-null  object
 6   City                          145898 non-null  object
 7   Date                          145898 non-null  object
 8   Day_of_Week                   145898 non-null  int64
 9   Month                         145898 non-null  int64
 10  Quarter                       145898 non-null  int64
 11  Is_Weekend                    145898 non-null  bool
 12  Is_Holiday                    145898 non-null  bool
 13  Festival_Name                 14484 non-null   object
 14  Days_Until_Next_Festival      145898 non-null  int64
 15  Is_Month_End                  145898 non-null  bool
 16  Days_Since_Launch             145898 non-null  int64
 17  Days_Since_Last_Price_Change  145898 non-null  int64
 18  MRP                           145898 non-null  float64
 19  Cost_Price                    145898 non-null  float64
 20  Current_Price                 145898 non-null  float64
 21  Discount_Pct                  145898 non-null  float64
 22  Margin_Pct                    145898 non-null  float64
 23  Min_Allowed_Price             145898 non-null  float64
 24  Max_Allowed_Price             145898 non-null  float64
 25  Marketplace_Fee_Pct           145898 non-null  float64
 26  Stock_Level                   145898 non-null  int64
 27  Reorder_Point                 145898 non-null  int64
 28  Lead_Time_Days                145898 non-null  int64
 29  Stock_Out_Risk                145898 non-null  float64
 30  Warehouse_ID                  145898 non-null  object
 31  Restock_Cost                  145898 non-null  float64
 32  Temperature                   145898 non-null  float64
 33  Humidity                      145898 non-null  float64
 34  Rainfall                      145898 non-null  float64
 35  Weather_Type                  145898 non-null  object
 36  Is_Extreme_Weather            145898 non-null  bool
 37  USD_INR                       145898 non-null  float64
 38  Crude_Oil_Price_USD           145898 non-null  float64
 39  Gold_Price                    145898 non-null  float64
 40  Inflation_Index               145898 non-null  float64
 41  Consumer_Confidence_Proxy     145898 non-null  float64
 42  Competitor_Avg_Price          145898 non-null  float64
 43  Competitor_Min_Price          145898 non-null  float64
 44  Price_Gap_Pct                 145898 non-null  float64
 45  Competitor_Stock_Status       145898 non-null  object
 46  Competitor_Discount_Pct       145898 non-null  float64
 47  Market_Rank                   145898 non-null  int64
 48  Views                         145898 non-null  int64
 49  Clicks                        145898 non-null  int64
 50  Cart_Adds                     145898 non-null  int64
 51  Orders                        145898 non-null  int64
 52  Conversion_Rate               145898 non-null  float64
 53  Search_Trend_Index            145898 non-null  float64
 54  Demand_Index                  145898 non-null  float64
 55  Return_Rate                   145898 non-null  float64
 56  Price_Lag_7                   145898 non-null  float64
 57  Demand_Lag_7                  145898 non-null  float64
 58  Rolling_Avg_Price_30d         145898 non-null  float64
 59  Price_Elasticity_Score        145898 non-null  float64
 60  Seasonality_Impact_Score      145898 non-null  float64
 61  Festival_Impact_Score         145898 non-null  float64
 62  Weather_Impact_Score          145898 non-null  float64
 63  Price_Volatility_30d          145898 non-null  float64
 64  Price_to_Competitor_Ratio     145898 non-null  float64
 65  Stock_Days_Remaining          145898 non-null  float64
 66  Demand_Momentum_7d            145898 non-null  float64
 67  Revenue_Per_Unit              145898 non-null  float64
 68  Price_Rank_in_Category        145898 non-null  int64
 69  Fuel_Price_INR_Proxy          145898 non-null  float64
 70  Optimal_Price                 145898 non-null  float64
dtypes: bool(4), float64(40), int64(15), object(12)
memory usage: 75.1+ MB

In [8]:
df.isnull().sum()

Product_ID                0
Product_Name              0
Brand                     0
Category                  0
Subcategory               0
                         ..
Demand_Momentum_7d        0
Revenue_Per_Unit          0
Price_Rank_in_Category    0
Fuel_Price_INR_Proxy      0
Optimal_Price             0
Length: 71, dtype: int64

In [9]:
df.describe()

,Day_of_Week,Month,Quarter,Days_Until_Next_Festival,Days_Since_Launch,Days_Since_Last_Price_Change,MRP,Cost_Price,Current_Price,Discount_Pct,...,Festival_Impact_Score,Weather_Impact_Score,Price_Volatility_30d,Price_to_Competitor_Ratio,Stock_Days_Remaining,Demand_Momentum_7d,Revenue_Per_Unit,Price_Rank_in_Category,Fuel_Price_INR_Proxy,Optimal_Price
count,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000,...,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000,145898.000000
mean,3.008376,6.337208,2.452467,26.957313,328.028774,3.266015,1516.297783,745.453903,1230.880406,18.742947,...,0.666334,0.021138,65.103916,1.003383,3.376199,1.000074,327.399962,6.943097,110.116993,1476.681599
std,1.999767,3.327746,1.089386,27.837644,248.110917,2.325416,1346.671601,724.828510,1096.260989,5.108633,...,0.860920,0.257796,65.895021,0.058128,2.146577,0.070133,275.616698,4.776076,23.945152,1325.339838
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,120.000000,69.600000,86.570000,8.050000,...,0.000000,-1.000000,0.000000,0.768000,0.100000,0.670000,-22.030000,1.000000,82.090000,102.670000
25%,1.000000,4.000000,2.000000,6.000000,140.000000,1.000000,599.000000,263.560000,505.300000,14.460000,...,0.010000,0.000000,21.790000,0.966000,1.800000,0.960000,146.470000,3.000000,92.760000,578.812500
50%,3.000000,6.000000,2.000000,16.000000,280.000000,3.000000,1099.000000,570.000000,892.585000,18.590000,...,0.290000,0.000000,45.130000,1.000000,3.000000,1.000000,261.850000,6.000000,99.990000,1048.950000
75%,5.000000,9.000000,3.000000,39.000000,449.000000,5.000000,1999.000000,967.560000,1611.740000,23.020000,...,1.060000,0.000000,86.500000,1.036000,4.600000,1.040000,449.080000,11.000000,117.860000,1964.480000
max,6.000000,12.000000,4.000000,117.000000,1295.000000,11.000000,8999.000000,5219.420000,8085.230000,28.000000,...,3.000000,0.800000,638.150000,1.500000,18.200000,1.320000,2014.190000,18.000000,178.220000,9448.950000